# Generated by Django 4.0.5 on 2022-06-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0005_coments_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coments',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='coments',
            name='signature',
        ),
    ]
