# Generated by Django 4.0.5 on 2022-06-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0006_remove_coments_dia_remove_coments_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='dia',
            field=models.BooleanField(null=True),
        ),
    ]
