# Generated by Django 4.0.5 on 2022-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0008_rename_coments_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='signature',
            field=models.CharField(default='FirmaGay', max_length=100),
        ),
    ]
